"""
Project template generators for different technology stacks.
Each function returns a dict of files to be created.
"""

from typing import Dict, List


def get_nextjs_template(project_name: str, features: List[str]) -> Dict[str, str]:
    """Generate Next.js project template."""
    return {
        "package.json": f"""{{
  "name": "{project_name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "type-check": "tsc --noEmit"
  }},
  "dependencies": {{
    "react": "^18.3.0",
    "react-dom": "^18.3.0",
    "next": "^14.2.0"
  }},
  "devDependencies": {{
    "@types/node": "^20.12.0",
    "@types/react": "^18.3.0",
    "typescript": "^5.4.0",
    "tailwindcss": "^3.4.0",
    "postcss": "^8.2.0",
    "autoprefixer": "^10.4.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.0"
  }}
}}
""",
        "tsconfig.json": """{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "jsx": "preserve",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    },
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
""",
        ".eslintrc.json": """{
  "extends": "next/core-web-vitals",
  "rules": {}
}
""",
        ".gitignore": """# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env.local
.env.development.local
.env.test.local
.env.production.local

# vercel
.vercel
""",
        "next.config.js": """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = nextConfig
""",
        "tailwind.config.js": """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
""",
        "postcss.config.js": """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
""",
        "app/layout.tsx": """import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '{project_name}',
  description: 'Generated by AI Code Agent',
}

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode
}}) {{
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}}
""",
        "app/page.tsx": """'use client'

import Link from 'next/link'

export default function Home() {{
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">{project_name}</h1>
        <p className="text-xl text-gray-600 mb-8">Welcome to your Next.js application</p>
        <Link
          href="/api/hello"
          className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Test API
        </Link>
      </div>
    </main>
  )
}}
""",
        "app/globals.css": """@tailwind base;
@tailwind components;
@tailwind utilities;

html {{
  scroll-behavior: smooth;
}}

body {{
  background-color: #f9fafb;
}}
""",
        "app/api/hello/route.ts": """export async function GET() {
  return Response.json({
    message: 'Hello from {project_name}!',
    timestamp: new Date().toISOString(),
  })
}
""",
        ".env.example": """# Add your environment variables here
# NEXT_PUBLIC_API_URL=http://localhost:3000
""",
        "README.md": f"""# {project_name}

A modern Next.js application built with TypeScript and Tailwind CSS.

## Getting Started

### Prerequisites
- Node.js 18.x or higher
- npm or yarn

### Installation

1. Clone the repository
2. Install dependencies:
```bash
npm install
```

3. Create a `.env.local` file based on `.env.example`

4. Start the development server:
```bash
npm run dev
```

5. Open [http://localhost:3000](http://localhost:3000) in your browser

## Project Structure

- `app/` - Next.js app directory with routes
- `components/` - Reusable React components
- `public/` - Static assets
- `lib/` - Utility functions and helpers

## Available Scripts

- `npm run dev` - Start development server
- `npm run build` - Build for production
- `npm start` - Start production server
- `npm run lint` - Run ESLint

## Technologies Used

- **Next.js** - React framework
- **TypeScript** - Type safety
- **Tailwind CSS** - Styling
- **ESLint** - Code quality

## License

MIT
""",
    }


def get_fastapi_template(project_name: str, features: List[str]) -> Dict[str, str]:
    """Generate FastAPI project template."""
    return {
        "requirements.txt": """fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
pydantic-settings==2.1.0
sqlalchemy==2.0.23
python-dotenv==1.0.0
pytest==7.4.3
httpx==0.25.2
""",
        "main.py": f"""\"\"\"Main entry point for {project_name} FastAPI application.\"\"\"
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

# Import routers
from app.api import hello

# Lifespan context
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    print("Starting up {project_name}...")
    yield
    # Shutdown
    print("Shutting down {project_name}...")

# Create FastAPI app
app = FastAPI(
    title="{project_name}",
    description="FastAPI microservice",
    version="0.1.0",
    lifespan=lifespan,
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(hello.router, prefix="/api", tags=["health"])

@app.get("/")
async def root():
    \"\"\"Root endpoint.\"\"\"
    return {{"message": "Welcome to {project_name}!"}}

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )
""",
        "app/__init__.py": """""",
        "app/api/__init__.py": """""",
        "app/api/hello.py": """\"\"\"Hello API endpoint.\"\"\"
from fastapi import APIRouter
from pydantic import BaseModel
from datetime import datetime

router = APIRouter()


class HelloResponse(BaseModel):
    \"\"\"Response model for hello endpoint.\"\"\"
    message: str
    timestamp: datetime


@router.get("/hello", response_model=HelloResponse)
async def hello():
    \"\"\"Hello endpoint.\"\"\"
    return HelloResponse(
        message="Hello from FastAPI!",
        timestamp=datetime.now(),
    )


@router.get("/health")
async def health_check():
    \"\"\"Health check endpoint.\"\"\"
    return {"status": "healthy"}
""",
        "app/config.py": f"""\"\"\"Configuration settings for {project_name}.\"\"\"
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    \"\"\"Application settings.\"\"\"
    app_name: str = "{project_name}"
    debug: bool = True
    database_url: str = "sqlite:///./test.db"

    class Config:
        env_file = ".env"


settings = Settings()
""",
        ".env.example": """DEBUG=True
DATABASE_URL=sqlite:///./test.db
""",
        ".gitignore": """__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
venv/
ENV/
env/
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store
.pytest_cache/
.coverage
htmlcov/
.env
.env.local
""",
        "pytest.ini": """[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
""",
        "tests/__init__.py": """""",
        "tests/test_api.py": """\"\"\"Tests for API endpoints.\"\"\"
import pytest
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)


def test_read_root():
    \"\"\"Test root endpoint.\"\"\"
    response = client.get("/")
    assert response.status_code == 200
    assert "message" in response.json()


def test_health_check():
    \"\"\"Test health check endpoint.\"\"\"
    response = client.get("/api/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"
""",
        "Dockerfile": """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
""",
        "docker-compose.yml": """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
""",
        "README.md": f"""# {project_name}

A FastAPI microservice template.

## Getting Started

### Prerequisites
- Python 3.11+
- pip or conda

### Installation

1. Create a virtual environment:
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
```

2. Install dependencies:
```bash
pip install -r requirements.txt
```

3. Create `.env` from `.env.example`:
```bash
cp .env.example .env
```

4. Run the application:
```bash
python main.py
```

5. Open [http://127.0.0.1:8000/docs](http://127.0.0.1:8000/docs) for API documentation

## Running Tests

```bash
pytest
```

## Docker

Build and run with Docker:
```bash
docker-compose up
```

## Project Structure

- `main.py` - FastAPI application entry point
- `app/api/` - API route handlers
- `app/models/` - Database models (when added)
- `app/schemas/` - Pydantic schemas
- `tests/` - Unit and integration tests

## License

MIT
""",
    }


def get_django_template(project_name: str, features: List[str]) -> Dict[str, str]:
    """Generate Django project template."""
    safe_name = project_name.replace("-", "_")
    return {
        "requirements.txt": """Django==4.2.8
djangorestframework==3.14.0
django-cors-headers==4.3.1
psycopg2-binary==2.9.9
python-dotenv==1.0.0
pytest==7.4.3
pytest-django==4.7.0
pytest-cov==4.1.0
gunicorn==21.2.0
""",
        "manage.py": f"""#!/usr/bin/env python
\"\"\"Django's command-line utility for administrative tasks.\"\"\"
import os
import sys


def main():
    \"\"\"Run administrative tasks.\"\"\"
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{safe_name}.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
""",
        f"{safe_name}/__init__.py": """""",
        f"{safe_name}/settings.py": f"""\"\"\"Django settings for {project_name}.\"\"\"
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-in-production')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{safe_name}.urls'

TEMPLATES = [
    {{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {{
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }},
    }},
]

WSGI_APPLICATION = '{safe_name}.wsgi.application'

DATABASES = {{
    'default': {{
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }}
}}

AUTH_PASSWORD_VALIDATORS = [
    {{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}},
    {{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}},
    {{'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'}},
    {{'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
]

REST_FRAMEWORK = {{
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}}
""",
        f"{safe_name}/urls.py": f"""\"\"\"URL configuration for {project_name}.\"\"\"
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('app.urls')),
]
""",
        f"{safe_name}/wsgi.py": f"""\"\"\"WSGI config for {project_name}.\"\"\"
import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{safe_name}.settings')

application = get_wsgi_application()
""",
        "app/__init__.py": """""",
        "app/apps.py": f"""\"\"\"App configuration.\"\"\"
from django.apps import AppConfig


class AppConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'app'
""",
        "app/models.py": """\"\"\"Database models.\"\"\"
from django.db import models


class TimeStampedModel(models.Model):
    \"\"\"Abstract base model with timestamps.\"\"\"
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
""",
        "app/serializers.py": """\"\"\"DRF serializers.\"\"\"
from rest_framework import serializers


class HelloSerializer(serializers.Serializer):
    \"\"\"Simple hello message serializer.\"\"\"
    message = serializers.CharField()
    timestamp = serializers.DateTimeField()
""",
        "app/views.py": """\"\"\"API views.\"\"\"
from rest_framework.decorators import api_view
from rest_framework.response import Response
from datetime import datetime


@api_view(['GET'])
def hello(request):
    \"\"\"Hello endpoint.\"\"\"
    return Response({
        'message': 'Hello from Django!',
        'timestamp': datetime.now().isoformat(),
    })


@api_view(['GET'])
def health_check(request):
    \"\"\"Health check endpoint.\"\"\"
    return Response({'status': 'healthy'})
""",
        "app/urls.py": """\"\"\"App URL configuration.\"\"\"
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('health/', views.health_check, name='health'),
]
""",
        ".env.example": """SECRET_KEY=your-secret-key-here
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1
DATABASE_URL=sqlite:///./db.sqlite3
""",
        ".gitignore": """__pycache__/
*.py[cod]
*.so
.Python
build/
db.sqlite3
.venv/
venv/
ENV/
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store
.pytest_cache/
.coverage
htmlcov/
.env
.env.local
""",
        "README.md": f"""# {project_name}

A Django REST Framework project.

## Getting Started

### Prerequisites
- Python 3.11+
- pip or conda

### Installation

1. Create a virtual environment:
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
```

2. Install dependencies:
```bash
pip install -r requirements.txt
```

3. Copy `.env.example` to `.env` and update settings:
```bash
cp .env.example .env
```

4. Run migrations:
```bash
python manage.py migrate
```

5. Create a superuser:
```bash
python manage.py createsuperuser
```

6. Run the development server:
```bash
python manage.py runserver
```

7. Access the admin at [http://localhost:8000/admin](http://localhost:8000/admin)
8. Access the API at [http://localhost:8000/api](http://localhost:8000/api)

## Running Tests

```bash
pytest
```

## Project Structure

- `{safe_name}/` - Project settings and configuration
- `app/` - Main application with models, views, serializers
- `manage.py` - Django management script

## License

MIT
""",
    }


# Mapping of technology to template generators
TECH_GENERATORS = {
    "nextjs": get_nextjs_template,
    "fastapi": get_fastapi_template,
    "django": get_django_template,
}


def get_template(tech: str, project_name: str, features: List[str]) -> Dict[str, str]:
    """Get template files for a technology."""
    generator = TECH_GENERATORS.get(tech)
    if not generator:
        return {"README.md": f"# {project_name}\n\nProject template for {tech}"}

    return generator(project_name, features)
